spring:

  #静态资源处理
  # thymeleaf 关闭缓存
  thymeleaf:
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&severTimeZone=Asia/shanghai
    username: root
    password: root
    hikari:
      #连接池名字
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认为10分钟
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #最大存活时间，0表示永久存活，默认180000
      max-lifetime: 180000
      #连接超时时间
      connection-timeout: 30000
      #心跳机制，测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms

  session:
    store-type: redis
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: false
        #启用压缩资源
        compressed: true
        #启用h5应用缓存
      add-mappings: true
      static-locations: classpath:/static/
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    #虚拟主机
    virtual-host: /
    port: 5672

    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者的最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完载处理吓一条
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #当消息被拒绝时，是否重新进入对列
        default-requeue-rejected: true

    template:
      retry:
        #开启重试
        enabled: true
        #重试时间
        initial-interval: 1000ms
        #c重试次数
        max-attempts: 3



#mybatis-plus 配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据类型的别名
  type-aliases-package: com.zd.seckill.pojo

# Mybatis SqL打印，方法接口所在的包，不是Mapper.xml所在的包
logging:
  level:
    com.zd.seckill.mapper: debug


